# Dependabot設定
# 依存関係の自動更新

version: 2
updates:
  # Python依存関係
  - package-ecosystem: "pip"
    directory: "/backend/layers/common"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "WhiteRabbit210"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "WhiteRabbit210"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"